services:
  dispatcher:
    build:
      dockerfile: dispatcher.Dockerfile
    env_file:
      - ".env"
    ports:
     - "8200:8200"
  runner:
    build:
      dockerfile: runner.Dockerfile
    env_file:
      - ".env"
    expose:
      - "8201"
